version: "3.9"
services:
    poe-kafka-consumer:
        build: .
        ports:
            - "3001:3001"
        links:
            - mongo:mongo
    mongo:
        image: mongo
        restart: always
        ports:
           - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: your_mongo_user
            MONGO_INITDB_ROOT_PASSWORD: your_mongo_pw
            
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 3002:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: your_mongo_user
            ME_CONFIG_MONGODB_ADMINPASSWORD: your_mongo_pw
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock